development:
  adapter: mysql2
  database: my_database_development
  username: root
  password:
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  username: root
  password:
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
