development:
  adapter: mysql2
  database: reservester_development
  username: root
  password:
    pool: 5
  timeout: 5000
  host: 127.0.0.1
  port: 3306
test:
  adapter: mysql2
  username: root
  password:
    database: reservester_test
  pool: 5
  timeout: 5000
  host: 127.0.0.1
  port: 3306

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
